name: Deploy Flutter Web ke GitHub Pages

on:
  # Memicu workflow setiap kali ada push ke branch 'main'
  push:
    branches: [ "main" ] # Ganti 'main' jika branch utama Anda 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        # PENTING: Pastikan nama repositori ini BENAR!
        run: flutter build web --base-href="/AplikasiManagementONIC/"

      - name: Deploy to GitHub Pages
        # Action ini yang akan membuat branch 'gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web